#!/usr/bin/env bash
#
# Builds the documentation site into site/dist.
#
# The two specification pages are rendered from the same Markdown the
# repository ships, and cli.json is generated by running the binary, so the
# site cannot document a format or a flag that does not exist.
#
# Usage:
#   ./scripts/build-site.sh            # build
#   ./scripts/build-site.sh --serve    # build, then serve it locally
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$PWD"
SERVE=0
PORT=8000

for arg in "$@"; do
  case "$arg" in
    --serve) SERVE=1 ;;
    --port=*) PORT="${arg#--port=}" ;;
    -h|--help)
      sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "build-site.sh: unknown option $arg" >&2
      exit 2
      ;;
  esac
done

printf '\033[1m==> building slidepack\033[0m\n'
BIN="$(mktemp -d)/slidepack"
go build -o "$BIN" ./cmd/slidepack

printf '\n\033[1m==> generating site\033[0m\n'
cd site
go run . -bin "$BIN" -out dist
cd "$ROOT"

printf '\n\033[32m==> site/dist is ready\033[0m\n'

if [[ "$SERVE" == "1" ]]; then
  printf '\n\033[1m==> serving on http://localhost:%s\033[0m\n' "$PORT"
  # Only for local preview. GitHub Pages serves the same directory verbatim.
  cd site/dist && exec python3 -m http.server "$PORT"
fi
