// Package envelope writes and reads the HTML container of a packed
// presentation.
//
// The container is deliberately boring: fixed marker comment, one <script>
// holding the JSON manifest, one <script> holding the single base64 payload,
// one <script> holding the runtime. Locating those three elements needs a
// substring search, not an HTML parser, which is what lets `slidepack unpack`
// identify a slidepack file without interpreting arbitrary markup.
package envelope

import (
	"bufio"
	"bytes"
	"encoding/base64"
	"errors"
	"fmt"
	"html"
	"io"
	"strings"

	"github.com/pwagstro/slidepack/internal/manifest"
	"github.com/pwagstro/slidepack/internal/runtime"
)

// Marker is the sentinel comment that identifies a packed presentation.
const Marker = "<!-- SLIDEPACK FORMAT 1 -->"

// Element IDs. These are part of the format contract; see docs/format-v1.md.
const (
	ManifestID = "slidepack-manifest"
	PayloadID  = "slidepack-payload"
	RuntimeID  = "slidepack-runtime"
	StatusID   = "slidepack-status"
	StyleID    = "slidepack-bootstrap-style"
)

// WriteOptions configures the document that Write produces.
type WriteOptions struct {
	// Manifest is serialised into the manifest element. Its payload digest and
	// sizes must already be filled in.
	Manifest *manifest.Manifest
	// Title becomes the outer document's <title>, so that the browser tab is
	// correct before any JavaScript runs. Usually the presentation's own title.
	Title string
	// Payload is the raw gzip stream; Write base64-encodes it on the fly.
	Payload io.Reader
}

// Write streams a complete packed presentation to w.
//
// The payload is encoded straight from the reader into the writer, so the
// encoder never holds more than a few kilobytes regardless of how large the
// presentation is.
func Write(w io.Writer, opts WriteOptions) error {
	if err := runtime.Check(); err != nil {
		return err
	}
	mjson, err := opts.Manifest.Marshal()
	if err != nil {
		return fmt.Errorf("serialising manifest: %w", err)
	}
	// Go's JSON encoder escapes <, > and & as <, > and & by
	// default, so a file named "</script>.png" cannot terminate the element.
	if bytes.Contains(bytes.ToLower(mjson), []byte("</script")) {
		return errors.New("internal error: manifest JSON contains a script-terminating sequence")
	}

	bw := bufio.NewWriterSize(w, 1<<16)

	title := strings.TrimSpace(opts.Title)
	if title == "" {
		title = "Presentation"
	}

	if _, err := io.WriteString(bw, header(title)); err != nil {
		return err
	}
	if _, err := bw.Write(mjson); err != nil {
		return err
	}
	if _, err := io.WriteString(bw, betweenManifestAndPayload); err != nil {
		return err
	}

	enc := base64.NewEncoder(base64.StdEncoding, bw)
	if _, err := io.Copy(enc, opts.Payload); err != nil {
		return fmt.Errorf("encoding payload: %w", err)
	}
	if err := enc.Close(); err != nil {
		return fmt.Errorf("finishing payload: %w", err)
	}

	if _, err := io.WriteString(bw, footer()); err != nil {
		return err
	}
	return bw.Flush()
}

func header(title string) string {
	var b strings.Builder
	b.WriteString("<!doctype html>\n")
	b.WriteString(`<html lang="en">` + "\n")
	b.WriteString("<head>\n")
	b.WriteString(`<meta charset="utf-8">` + "\n")
	b.WriteString(`<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">` + "\n")
	b.WriteString(`<meta name="generator" content="slidepack format 1">` + "\n")
	b.WriteString("<title>" + html.EscapeString(title) + "</title>\n")
	b.WriteString(Marker + "\n")
	b.WriteString(generatedNotice)
	b.WriteString(`<style id="` + StyleID + `">` + "\n")
	b.WriteString(runtime.CSS())
	b.WriteString("</style>\n")
	b.WriteString("</head>\n")
	b.WriteString("<body>\n")
	b.WriteString(statusBlock)
	b.WriteString(`<script id="` + ManifestID + `" type="application/json">` + "\n")
	return b.String()
}

const generatedNotice = `<!--
  Generated by slidepack. This file is a compiled distribution artifact.

  The presentation source is the single base64 payload below; editing this
  document by hand will not survive the next pack, and reading the payload is
  not a useful way to inspect the presentation. Instead:

      slidepack unpack this-file.html -o ./presentation
      ... edit ./presentation ...
      slidepack pack ./presentation -o this-file.html

  Opening this file runs the JavaScript it contains. Only open presentations
  from sources you trust.
-->
`

const statusBlock = `<div id="` + StatusID + `">
<p class="slidepack-loading"><span class="slidepack-spinner"></span>Loading presentation&#8230;</p>
<noscript><style>.slidepack-loading{display:none}</style><div class="slidepack-panel"><p class="slidepack-title">This presentation needs JavaScript.</p><p class="slidepack-footnote">A slidepack presentation stores its slides, styles, images and fonts in a compressed archive inside this file, and expands that archive in the browser. Enable JavaScript for this page, or run <code>slidepack unpack</code> to recover the original source files.</p></div></noscript>
</div>
`

const betweenManifestAndPayload = `
</script>
<script id="` + PayloadID + `" type="application/octet-stream" data-format="tar" data-compression="gzip" data-encoding="base64">
`

func footer() string {
	var b strings.Builder
	b.WriteString("\n</script>\n")
	b.WriteString(`<script id="` + RuntimeID + `">` + "\n")
	b.WriteString(runtime.JS())
	b.WriteString("</script>\n")
	b.WriteString("</body>\n")
	b.WriteString("</html>\n")
	return b.String()
}

/* ------------------------------------------------------------------ */
/* Reading                                                             */
/* ------------------------------------------------------------------ */

// Document is a parsed packed presentation.
type Document struct {
	// ManifestJSON is the raw text of the manifest element.
	ManifestJSON []byte
	// PayloadBase64 is the raw text of the payload element, whitespace trimmed.
	PayloadBase64 []byte
	// PayloadAttrs are the data-* attributes declared on the payload element.
	PayloadAttrs map[string]string
}

// ErrNotSlidepack means the file is not a packed slidepack presentation.
var ErrNotSlidepack = errors.New("not a slidepack presentation")

// Parse locates the manifest and payload elements in a packed document.
func Parse(doc []byte) (*Document, error) {
	if !bytes.Contains(doc, []byte(Marker)) {
		// The marker is checked first so that an ordinary HTML file produces a
		// clear "this is not a slidepack file" rather than a confusing report
		// about a missing element.
		return nil, fmt.Errorf("%w: the %s marker is absent", ErrNotSlidepack, Marker)
	}
	_, mbody, err := findScript(doc, ManifestID)
	if err != nil {
		return nil, err
	}
	ptag, pbody, err := findScript(doc, PayloadID)
	if err != nil {
		return nil, err
	}
	return &Document{
		ManifestJSON:  bytes.TrimSpace(mbody),
		PayloadBase64: bytes.TrimSpace(pbody),
		PayloadAttrs:  parseAttrs(ptag),
	}, nil
}

// findScript returns the opening tag and the body of the <script> element with
// the given id.
//
// The search anchors on the id attribute and then walks backwards to the
// element's "<script", which tolerates attribute reordering without needing a
// real parser. Both the manifest (JSON with < escaped) and the payload (base64)
// are guaranteed not to contain "</script", so the first one found ends the
// element.
func findScript(doc []byte, id string) (tag, body []byte, err error) {
	start := -1
	for _, form := range [][]byte{
		[]byte(`id="` + id + `"`),
		[]byte(`id='` + id + `'`),
		[]byte(`id=` + id),
	} {
		if i := bytes.Index(doc, form); i >= 0 {
			start = i
			break
		}
	}
	if start < 0 {
		return nil, nil, fmt.Errorf("%w: no element with id %q", ErrNotSlidepack, id)
	}
	open := bytes.LastIndex(doc[:start], []byte("<script"))
	if open < 0 {
		return nil, nil, fmt.Errorf("malformed envelope: id %q is not on a <script> element", id)
	}
	if bytes.Contains(doc[open:start], []byte(">")) {
		return nil, nil, fmt.Errorf("malformed envelope: id %q is not inside a <script> start tag", id)
	}
	gt := bytes.IndexByte(doc[start:], '>')
	if gt < 0 {
		return nil, nil, fmt.Errorf("malformed envelope: unterminated <script> start tag for id %q", id)
	}
	contentStart := start + gt + 1
	end := bytes.Index(doc[contentStart:], []byte("</script"))
	if end < 0 {
		return nil, nil, fmt.Errorf("malformed envelope: unterminated <script> element for id %q", id)
	}
	return doc[open:contentStart], doc[contentStart : contentStart+end], nil
}

// parseAttrs pulls name="value" pairs out of a start tag.
func parseAttrs(tag []byte) map[string]string {
	out := map[string]string{}
	s := string(tag)
	i := 0
	for i < len(s) {
		eq := strings.IndexByte(s[i:], '=')
		if eq < 0 {
			break
		}
		eq += i
		// Walk back to the start of the attribute name.
		j := eq
		for j > 0 && !isSpaceByte(s[j-1]) {
			j--
		}
		name := strings.TrimSpace(s[j:eq])
		rest := s[eq+1:]
		if len(rest) == 0 {
			break
		}
		var value string
		if rest[0] == '"' || rest[0] == '\'' {
			q := rest[0]
			k := strings.IndexByte(rest[1:], q)
			if k < 0 {
				break
			}
			value = rest[1 : 1+k]
			i = eq + 1 + 1 + k + 1
		} else {
			k := 0
			for k < len(rest) && !isSpaceByte(rest[k]) && rest[k] != '>' {
				k++
			}
			value = rest[:k]
			i = eq + 1 + k
		}
		if name != "" {
			out[name] = value
		}
	}
	return out
}

func isSpaceByte(c byte) bool {
	return c == ' ' || c == '\t' || c == '\n' || c == '\r' || c == '\f'
}
